language: ruby
cache: bundler
rvm:
  - 2.1.7
  - 2.2.3
bundler_args: --without production
script: bundle exec rspec spec
services:
  - mongodb
env:
  - SECRET_KEY_BASE="abc123_test" DEVISE_SECRET_KEY="abc123_test"
